version: '3.8'

services:
  f5-tts-discord-bot:
    build: .
    container_name: f5-tts-discord-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./src/config:/app/src/config
    environment:
      - NODE_ENV=production